import {Category, Status} from "./models";

export const categories: Category[] = [
    {
        categoryName: "💥 Больше / Меньше",
        description: "В этой категории тебе нужно определить, что из предложенных вариантов больше",
        questions: [
            {
                question: "Что больше bool или integer?",
                pollId: "",
                answer: -1,
                points: 100,
                duration: 10,
                correctIndex: 1,
                status: Status.Created,
                options: ["Bool", "Integer"],
            },
            {
                question: "Максимальное число этого типа больше?",
                pollId: "",
                answer: -1,
                points: 200,
                duration: 12,
                correctIndex: 0,
                status: Status.Created,
                options: ["unsigned int 8", "int 8"],
            },
            {
                question: "Что больше?",
                pollId: "",
                answer: -1,
                points: 300,
                duration: 15,
                correctIndex: 0,
                status: Status.Created,
                options: ["2^16", "65535"],
            },
            {
                question: "Что больше?",
                pollId: "",
                answer: -1,
                points: 400,
                duration: 15,
                correctIndex: 2,
                status: Status.Created,
                options: ["4000MB", "2^32 bytes"],
            },
            {
                question: "Что больше?",
                pollId: "",
                answer: -1,
                points: 500,
                duration: 15,
                correctIndex: 0,
                status: Status.Created,
                options: [
                    "Количество языков в мире",
                    "Количество языков программирования",
                ],
            },
            {
                question: "Что больше?",
                pollId: "",
                answer: -1,
                points: 600,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: [
                    "Количество транзисторов в современном смартфоне",
                    "Количество звезд в галактике",
                ],
            },
            {
                question: "Что больше?",
                pollId: "",
                answer: -1,
                points: 700,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: [
                    "Данные хранящиеся в крупнейшей библиотеке мира",
                    "Объем данных, передаваемых в интернет за день",
                ],
            },
            {
                question: "Максимальное число этого типа больше",
                pollId: "",
                answer: -1,
                points: 800,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["int 64", "float 64"],
            },
            {
                question: "В байтах больше?",
                pollId: "",
                answer: -1,
                points: 900,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["JoePeach", "Жопич"],
            },
            {
                question: "Что больше?(timestamp)",
                pollId: "",
                answer: -1,
                points: 1000,
                duration: 20,
                correctIndex: 0,
                status: Status.Created,
                options: [
                    "31.01.2024 10:00:00(MSK, UTC+3)",
                    "31.01.2024 08:00:00(ICT, UTC+7)",
                ],
            },
        ],
    },
    {
        categoryName: "⏳ Раньше / Позже",
        description: "В этой категории тебе нужно определить какое событие произошло раньше или позже другого",
        questions: [
            {
                question: "Что появилось раньше?",
                pollId: "",
                answer: -1,
                points: 100,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["WWW", "TCP"],
            },
            {
                question: "Какой язык старше?",
                pollId: "",
                answer: -1,
                points: 200,
                duration: 15,
                correctIndex: 0,
                status: Status.Created,
                options: ["Pascal", "PHP", "Delphi"],
            },
            {
                question: "Какой формат появился раньше?",
                pollId: "",
                answer: -1,
                points: 300,
                duration: 15,
                correctIndex: 0,
                status: Status.Created,
                options: ["HLS", "DASH"],
            },
            {
                question: "Какой язык был создан в 90х?",
                pollId: "",
                answer: -1,
                points: 400,
                duration: 20,
                correctIndex: 3,
                status: Status.Created,
                options: ["Erlang", "C++", "С", "Python"],
            },
            {
                question: "Какая технология из 70х?",
                pollId: "",
                answer: -1,
                points: 500,
                duration: 20,
                correctIndex: 1,
                status: Status.Created,
                options: ["MySQL", "Oracle Database", "PostgreSQL", "IBM DB2"],
            },
            {
                question: "Кто старше Linux или UNIX?",
                pollId: "",
                answer: -1,
                points: 600,
                duration: 15,
                correctIndex: 0,
                status: Status.Created,
                options: ["Unix", "Linux"],
            },
            {
                question: "Кто старше Google или Yandex?",
                pollId: "",
                answer: -1,
                points: 700,
                duration: 15,
                correctIndex: 0,
                status: Status.Created,
                options: ["Yandex", "Google"],
            },
            {
                question: "Кто появился раньше USB3.0 или HDMI?",
                pollId: "",
                answer: -1,
                points: 800,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["USB3.0", "HDMI"],
            },
            {
                question: "Какой из языков появился не в 21 веке?",
                pollId: "",
                answer: -1,
                points: 900,
                duration: 20,
                correctIndex: 2,
                status: Status.Created,
                options: ["Rust", "Swift", "Ruby", "Zig"],
            },
            {
                question: "Какой из языков появился раньше?",
                pollId: "",
                answer: -1,
                points: 1000,
                duration: 20,
                correctIndex: 0,
                status: Status.Created,
                options: ["Go", "Rust", "Zig", "Carbon"],
            },
        ],
    },
    {
        categoryName: "🌙 Шареж Залоров",
        description: "В этой категории нужно продемонстрировать знание лора российского ит/около ит ютуба",
        questions: [
            {
                question: "Дополните фразу - прогрев ***",
                pollId: "",
                answer: -1,
                points: 100,
                duration: 15,
                correctIndex: 2,
                status: Status.Created,
                options: ["Кеша", "Печи", "Гоев", "Лидов"],
            },
            {
                question: "Кто такой Winderton?",
                pollId: "",
                answer: -1,
                points: 200,
                duration: 20,
                correctIndex: 1,
                status: Status.Created,
                options: ["Класс, который невозможно переопределить", "Блогер с контентом по С++"],
            },
            {
                question: "Кого не пропускает гейткиппер?",
                pollId: "",
                answer: -1,
                points: 300,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["Гоев", "Вкатунов"],
            },
            {
                question: "Чем знаменит Влад Тен?",
                pollId: "",
                answer: -1,
                points: 400,
                duration: 15,
                correctIndex: 0,
                status: Status.Created,
                options: ["Удалением канала", "Курсами по алгоритмам", "Подачей видео"],
            },
            {
                question: "О чем подкаст Мы обречены?",
                pollId: "",
                answer: -1,
                points: 500,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["Как развиваться в python", "Философствование на ИТ темы с гостями", "HR подкаст"],
            },
            {
                question: `"Здравствуйте мои дорогие.". Кто подобным образом начинает свои видео?`,
                pollId: "",
                answer: -1,
                points: 600,
                duration: 20,
                correctIndex: 3,
                status: Status.Created,
                options: ["Роман Сакутин", "IT декабрист", "Александр Ильин", "Сергей Немчинский"],
            },
            {
                question: "Кто из этих блогеров настойчиво предлагает греть 2ой стул?",
                pollId: "",
                answer: -1,
                points: 700,
                duration: 20,
                correctIndex: 1,
                status: Status.Created,
                options: [
                    "Роман Сакутин",
                    "Антон Назаров",
                    "Александр Ильин",
                    "Павел Дуров",
                    "Хауди Хо",
                ],
            },
            {
                question: `"Братан, хорош, давай, давай, вперёд! Контент в кайф, можно ещё? Вообще красавчик! Можно вот этого вот почаще?". Кто заканчивает видео этой фразой?`,
                pollId: "",
                answer: -1,
                points: 800,
                duration: 25,
                correctIndex: 1,
                status: Status.Created,
                options: ["Деми Мурыч", "Extreme Code", "Soer", "Сергей Немчинский"],
            },
            {
                question: "Кто из русскоязычного youtube блогеров переписал игру про динозаврика 5-6 раз",
                pollId: "",
                answer: -1,
                points: 900,
                duration: 20,
                correctIndex: 0,
                status: Status.Created,
                options: ["Хауди Хо", "Деми Мурыч", "Роман Сакутин", "ИТ декабрист"],
            },
            {
                question: "Какой язык, является доминирующим в роликах Деми Мурыч?",
                pollId: "",
                answer: -1,
                points: 1000,
                duration: 20,
                correctIndex: 3,
                status: Status.Created,
                options: ["С++", "Swift", "Python", "JavaScript"],
            },
        ]
    },
    {
        categoryName: "🎭 Титаны",
        description: "В этой категории речь пойдет о титанах ИТ индустрии",
        questions: [
            {
                question: "Кто основал Майрософт?",
                pollId: "",
                answer: -1,
                points: 100,
                duration: 15,
                correctIndex: 3,
                status: Status.Created,
                options: ["Мадам Кюри", "Роб Пайк", "Стив Джобс", "Билл Гейтс"],
            },
            {
                question: "Кто проводит презентации apple со смерти Джобса?",
                pollId: "",
                answer: -1,
                points: 200,
                duration: 20,
                correctIndex: 2,
                status: Status.Created,
                options: ["Trim Hook", "Стив Возняк", "Тим Кук", "Стив Балмер", "Тим Суинни"],
            },
            {
                question:
                    `"Итак, большинство из вас, скорее всего, будет невыносимо маяться от скуки в Рождество, и вот вам идеальное развлечение. Протестируйте 2.6.15-rc7". Кто автор высказывания?`,
                pollId: "",
                answer: -1,
                points: 300,
                duration: 25,
                correctIndex: 1,
                status: Status.Created,
                options: [
                    "Джон Ромеро",
                    "Линус Торвальдс",
                    "Тим Бернерс Ли",
                    "Брайан Керниган",
                    "Грэйдон Хор",
                ],
            },
            {
                question: "Кто автор языка С++",
                pollId: "",
                answer: -1,
                points: 400,
                duration: 15,
                correctIndex: 3,
                status: Status.Created,
                options: [
                    "Тодд Говард",
                    "Роб Пайк",
                    "Денис Ричи",
                    "Бьёрн Страуструп",
                    "Андерс Хейлсберг",
                ],
            },
            {
                question:
                    `Кто сказал - "Сюжет в игре — как сюжет в порнофильме. Он должен быть, но он не так уж важен"`,
                pollId: "",
                answer: -1,
                points: 500,
                duration: 20,
                correctIndex: 0,
                status: Status.Created,
                options: [
                    "Джон Кармак",
                    "Линус Торвольдс",
                    "Джей Абрамс",
                    "Джордж Лукас",
                ],
            },
            {
                question:
                    "Этот персонаж предсказывал цену биткоина в районе 500к долларов, иначе он съест свой член. Кто этот персонаж?",
                pollId: "",
                answer: -1,
                points: 600,
                duration: 25,
                correctIndex: 1,
                status: Status.Created,
                options: [
                    "Джон Кармак",
                    "Джон Макафи",
                    "Джон Резик",
                    "Джон Маккарти"
                ],
            },
            {
                question: "Кто автор HTTP, URI, HTML?",
                pollId: "",
                answer: -1,
                points: 700,
                duration: 20,
                correctIndex: 4,
                status: Status.Created,
                options: [
                    "Замир Безгоев",
                    "Линус Торвальдс",
                    "Денис Ричи",
                    "Джон Сноу",
                    "Бернерс Ли",
                    "Брайан Керниган",
                ],
            },
            {
                question: "Кто автор легендарной игры - Civilization",
                pollId: "",
                answer: -1,
                points: 800,
                duration: 15,
                correctIndex: 3,
                status: Status.Created,
                options: [
                    "Питер Мулинье",
                    "Адам Вест",
                    "Гай Ричи",
                    "Сид Мейер",
                    "Хидео Кодзима",
                ],
            },
            {
                question:
                    `Брайан Керниган сказал - "У каждого языка есть время жизни. За исключением ****, конечно"`,
                pollId: "",
                answer: -1,
                points: 900,
                duration: 20,
                correctIndex: 2,
                status: Status.Created,
                options: [
                    "За исключением его маман",
                    "За исключением фортран",
                    "За исключением кобол",
                    "За исключением ассемблера",
                ],
            },
            {
                question:
                    "Заходят как-то в бар физик, математик и программист. Физик говорит 6 5 8. Математик говорит 3 1 4. Что сказал программист?",
                pollId: "",
                answer: -1,
                points: 1000,
                duration: 25,
                correctIndex: 1,
                status: Status.Created,
                options: ["1 1 0", "0 1 1", "1 0 1"],
            },
        ],
    },
    {
        categoryName: "💤 Душница",
        description: "В этой категории может присутствовать духота. Лучше открыть форточку",
        questions: [
            {
                question: "Что значит абревиатура DDD",
                pollId: "",
                answer: -1,
                points: 100,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["Delivery Driven Development", "Domain Driven Development", "Decision Driven Development"],
            },
            {
                question: "Какой многозадачности не существует?",
                pollId: "",
                answer: -1,
                points: 200,
                duration: 15,
                correctIndex: 2,
                status: Status.Created,
                options: ["Кооперативная", "Вытесняющая", "Композитная"],
            },
            {
                question: "Уровень протокола ARP?",
                pollId: "",
                answer: -1,
                points: 300,
                duration: 15,
                correctIndex: 3,
                status: Status.Created,
                options: ["Прикладной", "Транспортный", "Сетевой", "Канальный"],
            },
            {
                question: "Какое дерево не существует?",
                pollId: "",
                answer: -1,
                points: 400,
                duration: 15,
                correctIndex: 3,
                status: Status.Created,
                options: ["Бинарное", "B-дерево", "Красно-черное", "Черно-белое"],
            },
            {
                question: "Алгоритм Бойера-Мура используется для?",
                pollId: "",
                answer: -1,
                points: 500,
                duration: 20,
                correctIndex: 1,
                status: Status.Created,
                options: ["Сортировки массивов", "Поиск на строках", "Поиск в графе", "Поиск в глубину"],
            },
            {
                question: "Какой паттерн микросервисной архитектуры придуманный?",
                pollId: "",
                answer: -1,
                points: 600,
                duration: 25,
                correctIndex: 3,
                status: Status.Created,
                options: ["Saga Pattern", "API Gateway", "Event Sourcing", "Service Miracle", "CQRS Pattern", "Circuit Breaker"],
            },
            {
                question: "Как расшифровывается VBR в кодировании видео?",
                pollId: "",
                answer: -1,
                points: 700,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["Verified Bit Rate", "Variable Bit Rate", "Virtual Bit Rate", "Video Bit Rate"],
            },
            {
                question: "Какой аллокатор памяти не существует?",
                pollId: "",
                answer: -1,
                points: 800,
                duration: 20,
                correctIndex: 2,
                status: Status.Created,
                options: ["Buddy Allocator", "Slab Allocator", "Vec Allocator", "Stack Allocator"],
            },
            {
                question: "Что за кодек HEVC?",
                pollId: "",
                answer: -1,
                points: 900,
                duration: 20,
                correctIndex: 2,
                status: Status.Created,
                options: ["MPEG-4", "h264", "h265", "h266", "VP9"],
            },
            {
                question: "Какой из этих языков не имеет GC?",
                pollId: "",
                answer: -1,
                points: 1000,
                duration: 20,
                correctIndex: 4,
                status: Status.Created,
                options: ["Python", "Ruby", "Go", "Java", "Swift"],
            },
        ]
    },
    {
        categoryName: "🎄 Secret",
        description: "В этой категории присутствуют вопросы разной направленности",
        questions: [
            {
                question: "Какой номер улицы совпал у главных героев Ирония Судьбы?",
                pollId: "",
                answer: -1,
                points: 100,
                duration: 15,
                correctIndex: 2,
                status: Status.Created,
                options: ["1", "2", "3", "4"],
            },
            {
                question: "Кто из них имеет отношение к программированию?",
                pollId: "",
                answer: -1,
                points: 200,
                duration: 15,
                correctIndex: 3,
                status: Status.Created,
                options: [
                    "Госпожа Дашида",
                    "Карди Би",
                    "Снегурочка",
                    "Ада Лавлейс",
                    "Мадам Кюри",
                ],
            },
            {
                question: "Какой камень не является камнем бесконечности?",
                pollId: "",
                answer: -1,
                points: 300,
                duration: 15,
                correctIndex: 2,
                status: Status.Created,
                options: ["Души", "Силы", "Власти", "Времени"],
            },
            {
                question: "Что не характерно для Деда Мороза?",
                pollId: "",
                answer: -1,
                points: 400,
                duration: 20,
                correctIndex: 3,
                status: Status.Created,
                options: [
                    "Ходить с внучкой",
                    "Носить шубу",
                    "Спрашивать за стихи",
                    "Передвигаться на оленях",
                ],
            },
            {
                question: "Какая алкогольная основа в Куба Либра?",
                pollId: "",
                answer: -1,
                points: 500,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["Водка", "Ром", "Виски", "Шампанское"],
            },
            {
                question: "В каких Ёлках был медведь?",
                pollId: "",
                answer: -1,
                points: 600,
                duration: 20,
                correctIndex: 2,
                status: Status.Created,
                options: ["Елки", "Елки2", "Елки1914", "Елки5"],
            },
            {
                question:
                    "Традиционно испанцы встречают Новый год, съедая 12 штук чего?",
                pollId: "",
                answer: -1,
                points: 700,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["Сардин", "Виноградин", "Сосисок"],
            },
            {
                question: "Как называется боязнь снега?",
                pollId: "",
                answer: -1,
                points: 800,
                duration: 15,
                correctIndex: 2,
                status: Status.Created,
                options: ["Погонофобия", "Коулрофобия", "Хионофобия"],
            },
            {
                question: `"Зима близко" - это девиз какой семьи в Игре престолов?`,
                pollId: "",
                answer: -1,
                points: 900,
                duration: 15,
                correctIndex: 0,
                status: Status.Created,
                options: ["Дом Старков", "Дом Баратеонов", "Дом Талли"],
            },
            {
                question: "Сколько лучей у снежинки?",
                pollId: "",
                answer: -1,
                points: 1000,
                duration: 15,
                correctIndex: 1,
                status: Status.Created,
                options: ["5", "6", "7", "9"],
            },
        ],
    },
];
